### PR TITLE
add symfony7 support

### PR DESCRIPTION
**Pull request by dozer111**

### CODE REVIEW

**Comment by wjzijderveld** [comment]
Maybe a weird question: but is there a reason you'd still want to use this with Symfony 7? 
Symfony has had built-in support for this for a while now: `$request->getPayload()->get('foo')`
See #65

**Comment by dozer111** [comment]
hmm, i need to migrate a lot of services(300+)

by the first time it more easier to just up the library

**Comment by dozer111** [comment]
yes, you are right. I don`t know about it

thank you

---

also i see that u would write about it in readme. This is better solutuion)

**Comment by dozer111** [comment]
symfony7 has same functionality. @see https://github.com/qandidate-labs/symfony-json-request-transformer/pull/66/files

**Pull request closed without merging**
